# Generated by Django 5.1.2 on 2024-11-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_item_image_carthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carthistory',
            name='product',
            field=models.CharField(max_length=255),
        ),
    ]
