# Generated by Django 5.1.2 on 2024-12-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_carthistory_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='carthistory',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carthistory',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
