# Generated by Django 5.1.2 on 2024-12-07 01:39

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_carthistory_ordered_carthistory_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='carthistory',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=''),
        ),
    ]
