# Generated by Django 5.1.2 on 2024-12-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_carthistory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.PositiveIntegerField()),
            ],
        ),
    ]
